version: '3'
services:
  database:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - '3333:3333'
    tty: true
    depends_on:
      - database
    volumes:
      - .:/home/app
      - /home/app/node_modules
